runtime: python27
api_version: 1
threadsafe: yes

libraries:
- name: jinja2
  version: latest

builtins:
- appstats: off

handlers:
- url: /v[0-9]+/(.*)
  static_files: static/\1
  upload: static/.*
  expiration: "365d"
  secure: always

- url: /ckeditor(/v[0-9]+)?/(.*)
  static_files: static/ckeditor/\2
  upload: static/ckeditor/.*
  expiration: "365d"
  secure: always

- url: /(favicon.ico|robots.txt)
  static_files: static/\1
  upload: static/(favicon.ico|robots.txt)
  expiration: "365d"
  secure: always

- url: /blog(/.*)?
  script: handlers.blog.app
  secure: always

- url: /admin(/.*)?
  script: handlers.admin.app
  secure: always

- url: /.*
  script: handlers.main.app
  secure: always
